version: '3.8'

services:
  backend:
    build: .
    container_name: incognito-app
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: npm start

  db:
    image: postgres:14
    container_name: incognito-db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
